# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  CI:
    uses: eclipse-lmos/.github/.github/workflows/ci.yml@pipeline
    permissions:
      contents: read
